azure:
  activedirectory:
    tenant-id: 7ebaa813-a477-4a79-b4e0-281ccec06ba8
    active-directory-groups: group1

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://us-cdbr-east-03.cleardb.com:3306/heroku_ca43daed6cbe877
    username: b316566d750994
    password: c73f98d0
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: 4ff64c65-d09a-4ed1-ac50-20b5283e8a41
            client-secret: ~P.Cn-~G6iY9LZX3F3xEKP89r4I22hh3~Q
            redirect_uri:https://beeware319.herokuapp.com/login/oauth2/code/

