azure:
  activedirectory:
    tenant-id: a4cb2b53-8d8a-427c-8ba5-bf86b999db4c
    active-directory-groups: group1

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
  datasource:
    url: jdbc:mysql://us-cdbr-east-03.cleardb.com:3306/heroku_ca43daed6cbe877
    username: b316566d750994
    password: c73f98d0
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: 7e5767e2-680a-4b9d-8e6e-17097ce6f204
            client-secret: dtZWOq.4H9G.id5NirKm4sq1i-M7I0-o~C
            redirect_uri: https://beeware319be.azurewebsites.net/login/oauth2/code/azure
