azure:
  activedirectory:
    tenant-id: a4cb2b53-8d8a-427c-8ba5-bf86b999db4c
    active-directory-groups: group1

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_panpal?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=America/Vancouver
    username: ppuser
    password: Password
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: 7e5767e2-680a-4b9d-8e6e-17097ce6f204
            client-secret: dtZWOq.4H9G.id5NirKm4sq1i-M7I0-o~C
            redirect_uri: https://beeware319.azurewebsites.net

